# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34e66f11a1df21c4487271fb5a9dfe1ee31ea4e35c0a62201c747473ffdca4fd464cfcea739c5f73e6cd70c5ee6e6a383ce5a7cf4663af6d06fa113da6b26a2

test:
  secret_key_base: 64c09cd577edb2b6f4db7661003ed8cda56cb8a2cf3cd23ee2f764d7e7b4ca46bb411b77f1b8bdb61edf00f23d36ba41c3ad1de02877575683de837a74381ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
